### ISSUE TITLE
Explore functionality for handling inputs that don't need to be converted in chromophores.py

### ISSUE THREAD

**Issue by JimmyRushing** [cmelab/morphct#9]
![Screen Shot 2021-06-17 at 2 31 56 PM](https://user-images.githubusercontent.com/66091001/122468297-c569c300-cf78-11eb-9eb0-42da59d130c5.png)

Original motivation for this issue stems from this error.

**Comment by jennyfothergill** [comment]
thanks for the heads up @JimmyRushing! This issue is fixed by ef6101c074b2822dc1f97a770fd0b3dbca8eff0a

**Comment by jennyfothergill** [comment]
fixed by merging #3
